[package]
name = "neguse-taglib"
version = "0.1.0"
authors = ["hedgehog <hedgehog_online@outlook.com>"]
edition = "2018"

[dependencies]
encoding = "0"
regex = "1"
lazy_static = "1"
base64 = "0"
chrono = { version = "0", optional = true }
crc = "1"
